In [1]:
import numpy as np

In [24]:
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix_b = np.array([
    [7, 8, 9],
    [10, 11, 12],
])
matrix_sum = matrix_a + matrix_b
print('Sum:', matrix_sum)
print('-----')
matrix_diff = matrix_a - matrix_b
print('Diff:', matrix_diff)
print('-----')
matrix_multi = matrix_a * matrix_b
print('Multi:', matrix_multi)
print('-----')
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(3, 2)
print('Dot:', np.dot(a, b))
print('-----')
print(a.T)
print('-----')
a_squ = np.array([[1, 2], [5, 6]])
print(np.linalg.det(a_squ))  # Determination of square array
# 2x2: [[2, 1], [3, 4]] has a determinant of (2 * 4) - (1 * 3) = 5.
print('-----')
print('inverse:', np.linalg.inv(a_squ))
print('-----')
coefficients = np.array([[3, 1], [1, 2]])
constants = np.array([9, 8])
print(np.linalg.solve(coefficients, constants)) # X = A**-1 * B

Sum: [[ 8 10 12]
 [14 16 18]]
-----
Diff: [[-6 -6 -6]
 [-6 -6 -6]]
-----
Multi: [[ 7 16 27]
 [40 55 72]]
-----
Dot: [[ 58  64]
 [139 154]]
-----
[[1 4]
 [2 5]
 [3 6]]
-----
-3.999999999999999
-----
inverse: [[-1.5   0.5 ]
 [ 1.25 -0.25]]
-----
[2. 3.]
